ihpc=read.table("household_power_consumption.txt",header=T,na.strings = "?",sep=";",stringsAsFactors = FALSE)
str(ihpc)
ihpc$Date=as.Date(ihpc$Date,format="%d/%m/%Y")
str(ihpc)
ihpc=subset(ihpc,Date >="2007-02-01" & Date<="2007-02-02")
str(ihpc)
ihpc$datetime <- strptime(paste(ihpc$Date,ihpc$Time),"%Y-%m-%d %H:%M:%S",tz="")
str(ihpc)
with(ihpc,plot(datetime,Global_active_power,type="n",ylab="Global Active Power (kilowatts)",xlab=""))
with(ihpc,lines(datetime,Global_active_power))