ihpc=read.table("household_power_consumption.txt",header=T,na.strings = "?",sep=";",stringsAsFactors = FALSE)
str(ihpc)
ihpc$Date=as.Date(ihpc$Date,format="%d/%m/%Y")
str(ihpc)
ihpc=subset(ihpc,Date >="2007-02-01" & Date<="2007-02-02")
str(ihpc)
ihpc$datetime <- strptime(paste(ihpc$Date,ihpc$Time),"%Y-%m-%d %H:%M:%S",tz="")
str(ihpc)
with(ihpc,plot(datetime,Sub_metering_1,type="n",ylab="Energy sub metering",xlab=""))
with(ihpc,lines(datetime,Sub_metering_2,col="red"))
with(ihpc,lines(datetime,Sub_metering_3,col="blue"))
with(ihpc,lines(datetime,Sub_metering_1,col="black"))
legend("topright",pch="_",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.8)